# DIMENSIONS
WIDTH:int = 600
HEIGHT:int = 600

# ROW AND COLUMNS
ROWS:int = 3
COLS:int = 3

# CIRCLE , LINE AND CROSS_LINE WIDTH
LINE_WIDTH:int = 15
CIRC_WIDTH:int = 15
CROSS_WIDTH:int = 20

# DIVIDE DIMENSION TO BUILD GAME BOARD
SQSIZE:int = WIDTH//ROWS

# OFFSET
OFFSET:int = 50

# CIRCLE RADIUS
RADIUS:int = SQSIZE // 4

# COLOR
BG_COLOR:str = '#001d3d'
CIRC_COLOR:str = '#f9f9f9'
LINE_COLOR:str = '#003566'
CROSS_COLOR:str = '#ff6392'
